spring.application.name=Course-Management-System

# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/course_management_system
spring.datasource.username=postgres
spring.datasource.password=33333

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update

# SQL LOG
spring.jpa.show-sql=true